# Site Settings
title: Khunlagash
description: Magic codex.
author: WIL-TZY

# Base URL (for sites hosted at a subdirectory, e.g., username.github.io/repository)
# Uncomment and set the baseurl if the site is not at the root of the domain
baseurl: "/khunlagash"
url: ""

# Theme
#theme: jekyll-theme-minimal

# Navigation Links
nav:
  - title: Home
    url: /
  - title: Codex
    url: /codex
  - title: Magias
    url: /codex/magias

permalink: pretty
